Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OtisClientes.Data;
using OtisClientes.Models;
using System.Linq;
using System.Threading.Tasks;

namespace OtisClientes.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class AdministrationController : Controller
    {
        private readonly UserManager<UsuarioNet> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly OTISClientesContext _context;
        private readonly ILogger<AuthController> _logger;
        public AdministrationController(UserManager<UsuarioNet> userManager, RoleManager<IdentityRole> roleManager, OTISClientesContext context, ILogger<AuthController> logger)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
            _logger = logger;
        }
        // Usuarios
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _userManager.Users.ToListAsync());
        }
        // Creacion de usuarios
        [HttpGet]
        public IActionResult CreateUser()
        {
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUser([Bind("UserName,IdDepartamento")] UsuarioNet usuario)
        {
            //usuario.Email = "admin@gmail.com";
            usuario.CodigoEdificio = "-1";
            string password = "User123*";
            IdentityResult result = await _userManager.CreateAsync(usuario, password);
            if (result.Succeeded)
            {
                //_ = await _userManager.AddToRoleAsync(usuario, "Administrador");
                //_logger.LogInformation($"Usuario {usuario.UserName} con rol");
                return RedirectToAction(nameof(Index));
            }
            else
            {
                //_logger.LogInformation($"Usuario {usuario.UserName} no pudo ser creado");
                return View(usuario);
            }
        }
        // Roles
        [HttpGet]
        public async Task<IActionResult> Roles()
        {
            _logger.LogInformation("Ver roles");
            return View(await _roleManager.Roles.OrderBy(x => x.NormalizedName).ToListAsync());
        }
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRole([Bind("Name")] IdentityRole rol)
        {
            IdentityResult result = await _roleManager.CreateAsync(rol);
            if (result.Succeeded)
            {
                //_logger.LogInformation($"Rol: {rol} creado");
                return RedirectToAction(nameof(Roles));
            }
            else
            {
                //_logger.LogWarning("Error al crear rol");
                return View(rol);
            }
        }
        //Cargar clientes en masa
        //[HttpPost]
        // public async Task<IActionResult> CargarClientes()
        // {
        //     //var result = await _userManager.CreateAsync(new UsuarioNet { Email = "visitante@gmail.com", UserName = "54321", CodigoEdificio = "-1", IdDepartamento = 5 });
        //     //if (result.Succeeded)
        //     //{
        //     //    var visitante = await _userManager.FindByEmailAsync("visitante@gmail.com");
        //     //    await _userManager.AddToRoleAsync(visitante, "Cliente");
        //     //}
        //     //var result2 = await _userManager.CreateAsync(new UsuarioNet { Email= "admin@gmail.com", UserName = "admin", CodigoEdificio = "-1", IdDepartamento = 5 });
        //     //if (result.Succeeded)
        //     //{
        //     //    var admin = await _userManager.FindByEmailAsync("admin@gmail.com");
        //     //    await _userManager.AddToRoleAsync(admin, "Administrador");
        //     //}

        //     // Caso duplicado Codigo Corto de Edificio: 10997
        //     // Crear Rol Administrador
        //     //await _roleManager.CreateAsync(new IdentityRole("Administrador"));
        //     // Crear Rol Cliente
        //     //await _roleManager.CreateAsync(new IdentityRole("Cliente"));
        //     // Cargar Edificios a crear usuarios
        //     //List<Edificio> edificios = await _context.Edificios.Where(m => m.IdCodigoEdificio == "20105-10997").AsNoTracking().ToListAsync();
        //     //foreach (var item in edificios)
        //     //{
        //     //    UsuarioNet usuario = new() { UserName = item.CodigoCorto, CodigoEdificio = item.IdCodigoEdificio, IdDepartamento = item.IdDepartamento };
        //     //    IdentityResult result = await _userManager.CreateAsync(usuario);
        //     //    if (result.Succeeded)
        //     //    {
        //     //        IdentityResult roladded = await _userManager.AddToRoleAsync(usuario, "Cliente");
        //     //        if (roladded.Succeeded)
        //     //        {
        //     //            _logger.LogInformation($"Usuario {usuario.UserName} con rol");
        //     //        }
        //     //    }
        //     //}
        //     return Ok();
        // }
        //[HttpPost]
        //public async Task<IActionResult> CambiarPassword()
        //{
        //    try
        //    {
        //        IList<UsuarioNet>? usuariosClientes = await _userManager.GetUsersInRoleAsync("Administrador");
        //        foreach (UsuarioNet? item in usuariosClientes)
        //        {
        //            IdentityResult result = await _userManager.AddPasswordAsync(item, item.UserName);
        //            //IdentityResult result = await _userManager.ChangePasswordAsync(item, "", item.UserName);
        //            if (!result.Succeeded)
        //            {
        //                _logger.LogWarning(message: $"Ocurrio un error {item.UserName}");
        //            }
        //        }
        //    }
        //    catch (System.Exception)
        //    {
        //        throw;
        //    }
        //    return Ok();
        //}
    }
}

Views/Shared/_AdminPartial.cshtml
@inject SignInManager<UsuarioNet> SignInManager
@inject UserManager<UsuarioNet> UserManager
@if (@SignInManager.IsSignedIn(User))
{
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
        </li>
    @if (@User.IsInRole("Administrador"))
    {
        <li class="nav-item">
            <a class="nav-link text-light" asp-area="" asp-controller="Administration" asp-action="Index">Usuarios</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" asp-area="" asp-controller="Administration" asp-action="Roles">Roles</a>
        </li>
    }
    </ul>
}

Views/Shared/_Alert.cshtml
@if (TempData["AlertMsg"] != null)
{
    <script>
        @Html.Raw(TempData["AlertMsg"])
    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OTIS Bolivia</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OTISClientes.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/lib/intro.js/minified/introjs.min.css" />
    <link rel="stylesheet" href="~/lib/intro.js/themes/introjs-modern.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/dist/sweetalert2.min.css">
</head>
<body class="main-body">
    <header>
        <partial name="_NavBar" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - OTIS Bolivia
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/intro.js/minified/intro.min.js"></script>
    <script src="~/lib/sweetalert2/dist/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Html.PartialAsync("_Alert")
</body>
</html>

Views/Shared/_NavBar.cshtml
@inject SignInManager<UsuarioNet> SignInManager
@inject UserManager<UsuarioNet> UserManager

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OTIS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <partial name="_AdminPartial" />
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>